version: "3.6"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 7000:7000
      - "25:25"
    depends_on:
      - db
    networks:
      - app-net
  db:
    image: "postgres:11.2"
    ports:
      - 5432:5432
    volumes:
#      #- /data/brs:/data/brs
      - ./db_init/db_create.sh:/docker-entrypoint-initdb.d/db_create.sh
#      #- ./db_init/init_app_db.sh:/init/init_app_db.sh
    environment:
      - TZ=Australia/Sydney
      - PGDATA=/data/brs/database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=AW#edr5tg

    networks:
      - app-net
networks:
  app-net:
