#  partner -   0001_initial.py
#  Description:
#  Author:           darshan
#  Created:          21 Dec. 2019
#  Source:           https://github.com/dartion/partner
#  License:          Copyright (c) 2019 DN - All Rights ReservedAll Rights Reserved
#                    Unauthorized copying of this file, via any medium is
#                    strictly prohibited. Proprietary and confidential

# Generated by Django 2.2 on 2019-12-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('phone_number', models.BigIntegerField()),
                ('phone_number_1', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_created_by', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_password_number', models.BigIntegerField(unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhysicalFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=100)),
                ('physical_status', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=40)),
                ('mothers_name', models.CharField(max_length=40)),
                ('guardians_name', models.CharField(max_length=40)),
                ('resident_of_country', models.CharField(max_length=40)),
                ('resident_of_state', models.CharField(max_length=40)),
                ('resident_of_city_or_village', models.CharField(max_length=40)),
                ('mother_tongue', models.CharField(max_length=40)),
                ('community', models.CharField(max_length=40)),
                ('caste', models.CharField(max_length=40)),
                ('native_place', models.CharField(max_length=40)),
                ('residential_address', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField(unique=True)),
                ('additional_info', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/profile')),
                ('horoscope_image', models.ImageField(blank=True, null=True, upload_to='media/horoscope')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=100, null=True)),
                ('smoking', models.CharField(blank=True, max_length=100, null=True)),
                ('alcholic_drinks', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_class', models.CharField(blank=True, max_length=100, null=True)),
                ('family_type', models.CharField(blank=True, max_length=100, null=True)),
                ('family_values', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_brothers', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_sisters', models.CharField(blank=True, max_length=100, null=True)),
                ('married', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileExpectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectations', models.CharField(blank=True, max_length=10000, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducationOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_or_diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_degree_or_diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('working_since', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('average_monthly_income', models.BigIntegerField(unique=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAstrologicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gothra', models.CharField(blank=True, max_length=100, null=True)),
                ('pravara', models.CharField(blank=True, max_length=100, null=True)),
                ('nakshatra', models.CharField(blank=True, max_length=100, null=True)),
                ('rashi', models.CharField(blank=True, max_length=100, null=True)),
                ('horoscope_matching', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoroscopeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horoscope_image', models.ImageField(blank=True, null=True, upload_to='media/horoscope')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
    ]
