# Generated by Django 2.2 on 2019-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAstrologicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gothra', models.CharField(blank=True, max_length=100, null=True)),
                ('pravara', models.CharField(blank=True, max_length=100, null=True)),
                ('nakshatra', models.CharField(blank=True, max_length=100, null=True)),
                ('rashi', models.CharField(blank=True, max_length=100, null=True)),
                ('horoscope_matching', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('phone_number', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducationOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_or_diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_degree_or_diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('working_since', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('average_monthly_income', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileExpectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectations', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_class', models.CharField(blank=True, max_length=100, null=True)),
                ('family_type', models.CharField(blank=True, max_length=100, null=True)),
                ('family_values', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_brothers', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_sisters', models.CharField(blank=True, max_length=100, null=True)),
                ('married', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHabbits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=100, null=True)),
                ('smoking', models.CharField(blank=True, max_length=100, null=True)),
                ('alcholic_drinks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=40)),
                ('mothers_name', models.CharField(max_length=40)),
                ('guardians_name', models.CharField(max_length=40)),
                ('resident_of_country', models.CharField(max_length=40)),
                ('resident_of_state', models.CharField(max_length=40)),
                ('resident_of_city_or_village', models.CharField(max_length=40)),
                ('mother_toungue', models.CharField(max_length=40)),
                ('community', models.CharField(max_length=40)),
                ('caste', models.CharField(max_length=40)),
                ('sub_caste', models.CharField(max_length=40)),
                ('native_place', models.CharField(max_length=40)),
                ('residential_address', models.CharField(max_length=40)),
                ('contact_number', models.BigIntegerField(unique=True)),
                ('additional_info', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhysicalFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=100)),
                ('physical_status', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
            ],
        ),
    ]
