# Generated by Django 2.2 on 2019-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191209_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalinfo',
            name='residential_address',
            field=models.CharField(max_length=200),
        ),
    ]
