#  partner -   0004_auto_20191210_2150.py
#  Description:
#  Author:           darshan
#  Created:          21 Dec. 2019
#  Source:           https://github.com/dartion/partner
#  License:          Copyright (c) 2019 DN - All Rights ReservedAll Rights Reserved
#                    Unauthorized copying of this file, via any medium is
#                    strictly prohibited. Proprietary and confidential

# Generated by Django 2.2 on 2019-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191210_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
