# Generated by Django 2.2 on 2019-11-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191125_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='reset_passwprd_number',
            new_name='reset_password_number',
        ),
    ]
