# Generated by Django 2.2 on 2019-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191210_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
