# Generated by Django 2.2 on 2019-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191210_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='submit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
