#  partner -   0005_profilebasicinfo_submit.py
#  Description:
#  Author:           darshan
#  Created:          21 Dec. 2019
#  Source:           https://github.com/dartion/partner
#  License:          Copyright (c) 2019 DN - All Rights ReservedAll Rights Reserved
#                    Unauthorized copying of this file, via any medium is
#                    strictly prohibited. Proprietary and confidential

# Generated by Django 2.2 on 2019-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191210_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='submit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
