# Generated by Django 2.2 on 2019-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profilebasicinfo_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasicinfo',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
