#  partner -   0006_auto_20191211_0657.py
#  Description:
#  Author:           darshan
#  Created:          21 Dec. 2019
#  Source:           https://github.com/dartion/partner
#  License:          Copyright (c) 2019 DN - All Rights ReservedAll Rights Reserved
#                    Unauthorized copying of this file, via any medium is
#                    strictly prohibited. Proprietary and confidential

# Generated by Django 2.2 on 2019-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profilebasicinfo_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasicinfo',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
