# Generated by Django 2.2 on 2019-11-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191127_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasicinfo',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
