# Generated by Django 2.2 on 2019-12-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191211_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileeducationoccupation',
            name='average_monthly_income',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
