# Generated by Django 2.2 on 2019-11-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191127_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonalinfo',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
    ]
