# Generated by Django 2.2 on 2019-11-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profilepersonalinfo_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepersonalinfo',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
