# Generated by Django 2.2 on 2019-11-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191128_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileastrologicalinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AddField(
            model_name='profileeducationoccupation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AddField(
            model_name='profilefamilydetails',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AddField(
            model_name='profilehabbits',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AddField(
            model_name='profilephysicalfeatures',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
    ]
