# Generated by Django 2.2 on 2019-12-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profilehabits_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefamilydetails',
            name='married',
        ),
        migrations.AddField(
            model_name='profilebasicinfo',
            name='married',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
