# Generated by Django 2.2 on 2019-11-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191128_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileexpectation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
    ]
