# Generated by Django 2.2 on 2019-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profileexpectation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='profile_created_by',
            field=models.CharField(default='brother', max_length=40),
            preserve_default=False,
        ),
    ]
