# Generated by Django 2.2 on 2019-12-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profilebasicinfo_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
