# Generated by Django 2.2 on 2019-12-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profilebasicinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasicinfo',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
