# Generated by Django 2.2 on 2019-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191201_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
