# Generated by Django 2.2 on 2019-12-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profilebasicinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebasicinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/profile_images'),
        ),
    ]
