# Generated by Django 2.2 on 2019-12-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191203_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebasicinfo',
            name='image',
        ),
    ]
