# Generated by Django 2.2 on 2019-12-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_profilebasicinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebasicinfo',
            name='images',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
