# Generated by Django 2.2 on 2019-12-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191203_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='jataka_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/jataka'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
