# Generated by Django 2.2 on 2019-12-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191203_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jataka_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/jataka'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
    ]
