# Generated by Django 2.2 on 2019-12-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191203_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ProfileImages',
        ),
    ]
