# Generated by Django 2.2 on 2019-12-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191203_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimages',
            name='title',
        ),
        migrations.AddField(
            model_name='profileimages',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='jataka_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/jataka/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
