# Generated by Django 2.2 on 2019-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191203_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='jataka_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/jataka'),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
    ]
