# Generated by Django 2.2 on 2019-12-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191204_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='JatakaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jataka_image', models.ImageField(blank=True, null=True, upload_to='media/jataka')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True)),
            ],
        ),
    ]
