# Generated by Django 2.2 on 2019-12-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_jatakaimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileastrologicalinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profileeducationoccupation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profileexpectation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profilefamilydetails',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profilehabbits',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profilepersonalinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='profilephysicalfeatures',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileBasicInfo', unique=True),
        ),
    ]
